
CREATE OR REPLACE DATABASE BANK_ORG;
CREATE OR REPLACE DATABASE INSURER_ORG;
CREATE OR REPLACE DATABASE SHARED_ZONE;

CREATE OR REPLACE TABLE BANK_ORG.PUBLIC.CLIENT_RISK (
    HASHED_ID STRING,
    AGE_GROUP STRING,
    CREDIT_SCORE NUMBER,
    IS_DEFAULTED BOOLEAN
);

CREATE OR REPLACE TABLE INSURER_ORG.PUBLIC.CLAIMS (
    HASHED_ID STRING,
    CLAIM_AMOUNT NUMBER,
    POLICY_TYPE STRING
);
INSERT INTO BANK_ORG.PUBLIC.CLIENT_RISK VALUES
('user_abc_123', '18-25', 650, FALSE),
('user_def_456', '26-35', 710, FALSE),
('user_ghi_789', '18-25', 580, TRUE),
('user_jkl_012', '36-45', 800, FALSE);

INSERT INTO INSURER_ORG.PUBLIC.CLAIMS VALUES
('user_abc_123', 5000, 'Health'),
('user_def_456', 0, 'Auto'),
('user_ghi_789', 12000, 'Health'),
('user_jkl_012', 200, 'Life');

CREATE OR REPLACE MASKING POLICY SHARED_ZONE.PUBLIC.HIDE_ID AS (val string) 
  RETURNS string -> '*********'; 

ALTER TABLE BANK_ORG.PUBLIC.CLIENT_RISK 
MODIFY COLUMN HASHED_ID SET MASKING POLICY SHARED_ZONE.PUBLIC.HIDE_ID;

ALTER TABLE INSURER_ORG.PUBLIC.CLAIMS 
MODIFY COLUMN HASHED_ID SET MASKING POLICY SHARED_ZONE.PUBLIC.HIDE_ID;
SELECT * FROM BANK_ORG.PUBLIC.CLIENT_RISK;

CREATE OR REPLACE SECURE VIEW SHARED_ZONE.PUBLIC.CROSS_ORG_INSIGHTS AS
SELECT 
    b.AGE_GROUP,
    AVG(b.CREDIT_SCORE) as avg_credit_score,
    SUM(i.CLAIM_AMOUNT) as total_insurance_claims,
    COUNT(DISTINCT b.HASHED_ID) as household_count
FROM BANK_ORG.PUBLIC.CLIENT_RISK b
JOIN INSURER_ORG.PUBLIC.CLAIMS i ON b.HASHED_ID = i.HASHED_ID
GROUP BY 1
HAVING COUNT(DISTINCT b.HASHED_ID) >= 3; 
CREATE STAGE SHARED_ZONE.PUBLIC.MODELS_STAGE;

USE ROLE ACCOUNTADMIN;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';
USE ROLE ACCOUNTADMIN;
USE DATABASE SHARED_ZONE;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE BANK_DATA (
    USER_ID INT,
    AGE_GROUP STRING,
    CREDIT_SCORE INT,
    HOUSEHOLD_COUNT INT
);

CREATE OR REPLACE TABLE INSURANCE_DATA (
    USER_ID INT,
    POLICY_TYPE STRING,
    TOTAL_CLAIMS INT,
    RISK_LEVEL STRING
);


INSERT INTO BANK_DATA (USER_ID, AGE_GROUP, CREDIT_SCORE, HOUSEHOLD_COUNT)
VALUES 
    (1, '18-25', 650, 1),
    (2, '26-35', 720, 2),
    (3, '36-45', 780, 4),
    (4, '46-55', 610, 3),
    (5, '55+', 740, 2);

INSERT INTO INSURANCE_DATA (USER_ID, POLICY_TYPE, TOTAL_CLAIMS, RISK_LEVEL)
VALUES 
    (1, 'Health', 1500, 'Medium'),
    (2, 'Auto', 500, 'Low'),
    (3, 'Life', 0, 'Low'),
    (4, 'Health', 8000, 'High'),
    (5, 'Home', 1200, 'Medium');
    SELECT * FROM SHARED_ZONE.PUBLIC.CROSS_ORG_INSIGHTS;
USE ROLE ACCOUNTADMIN;
USE DATABASE SHARED_ZONE;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE BANK_DATA (
    USER_ID INT,
    AGE_GROUP STRING,
    CREDIT_SCORE INT,
    HOUSEHOLD_COUNT INT
);

CREATE OR REPLACE TABLE INSURANCE_DATA (
    USER_ID INT,
    POLICY_TYPE STRING,
    TOTAL_CLAIMS INT,
    RISK_LEVEL STRING
);

INSERT INTO BANK_DATA (USER_ID, AGE_GROUP, CREDIT_SCORE, HOUSEHOLD_COUNT)
VALUES 
    (1, '18-25', 650, 1),
    (2, '26-35', 720, 2),
    (3, '36-45', 780, 4),
    (4, '46-55', 610, 3),
    (5, '55+', 740, 2);

INSERT INTO INSURANCE_DATA (USER_ID, POLICY_TYPE, TOTAL_CLAIMS, RISK_LEVEL)
VALUES 
    (1, 'Health', 1500, 'Medium'),
    (2, 'Auto', 500, 'Low'),
    (3, 'Life', 0, 'Low'),
    (4, 'Health', 8000, 'High'),
    (5, 'Home', 1200, 'Medium');
    SELECT * FROM SHARED_ZONE.PUBLIC.CROSS_ORG_INSIGHTS;
  USE ROLE ACCOUNTADMIN;
USE DATABASE SHARED_ZONE;
USE SCHEMA PUBLIC;

CREATE OR REPLACE VIEW SHARED_ZONE.PUBLIC.CROSS_ORG_INSIGHTS AS
SELECT 
    b.AGE_GROUP,
    AVG(b.CREDIT_SCORE) AS AVG_CREDIT_SCORE,
    SUM(i.TOTAL_CLAIMS) AS TOTAL_INSURANCE_CLAIMS,
    COUNT(b.USER_ID) AS HOUSEHOLD_COUNT
FROM BANK_DATA b
JOIN INSURANCE_DATA i ON b.USER_ID = i.USER_ID
GROUP BY b.AGE_GROUP;

SELECT * FROM SHARED_ZONE.PUBLIC.CROSS_ORG_INSIGHTS;  
USE ROLE ACCOUNTADMIN;
USE DATABASE SHARED_ZONE;
USE SCHEMA PUBLIC;

DROP TABLE IF EXISTS BANK_DATA;
DROP TABLE IF EXISTS INSURANCE_DATA;
DROP VIEW IF EXISTS CROSS_ORG_INSIGHTS;

CREATE TABLE BANK_DATA (
    USER_ID INT,
    AGE_GROUP STRING,
    CREDIT_SCORE INT,
    HOUSEHOLD_COUNT INT
);

CREATE TABLE INSURANCE_DATA (
    USER_ID INT,
    POLICY_TYPE STRING,
    TOTAL_CLAIMS INT,
    RISK_LEVEL STRING
);

INSERT INTO BANK_DATA VALUES 
    (1, '18-25', 650, 1), (2, '26-35', 720, 2), (3, '36-45', 780, 4), (4, '46-55', 610, 3), (5, '55+', 740, 2);

INSERT INTO INSURANCE_DATA VALUES 
    (1, 'Health', 1500, 'Medium'), (2, 'Auto', 500, 'Low'), (3, 'Life', 0, 'Low'), (4, 'Health', 8000, 'High'), (5, 'Home', 1200, 'Medium');

CREATE VIEW CROSS_ORG_INSIGHTS AS
SELECT 
    B.AGE_GROUP,
    B.CREDIT_SCORE AS AVG_CREDIT_SCORE,
    I.TOTAL_CLAIMS AS TOTAL_INSURANCE_CLAIMS,
    B.HOUSEHOLD_COUNT,
    I.RISK_LEVEL
FROM BANK_DATA B
INNER JOIN INSURANCE_DATA I ON B.USER_ID = I.USER_ID;

SELECT * FROM CROSS_ORG_INSIGHTS;